const configs = {
  default: [
    { id: 1, text: 'Child noises in the background', selected: false },
    { id: 2, text: 'Hello, hello?', selected: false },
    { id: 3, text: 'I need jumb in another call', selected: false },
    { id: 4, text: 'Can everyone go on mute', selected: false },
    { id: 5, text: 'Could you please get closer to the mic', selected: false },
    { id: 6, text: '(Load painful echo / feedback)', selected: false },
    { id: 7, text: 'Next slide, please.', selected: false },
    { id: 8, text: 'Can we take this offline?', selected: false },
    { id: 9, text: 'Is _____ on the call?', selected: false },
    {
      id: 10,
      text: 'Could you share this slides afterwards?',
      selected: false,
    },
    { id: 11, text: 'Can somebody grant presenter rights?', selected: false },
    { id: 12, text: 'Can you email that to everyone?', selected: false },
    { id: 13, text: 'CONF CALL BINGO', selected: true },
    { id: 14, text: 'Sorry, I had problems loging in', selected: false },
    { id: 15, text: '(Animal noises in the background)', selected: false },
    { id: 16, text: "Sorry I didn't found the conference id", selected: false },
    { id: 17, text: 'I was having connection issues', selected: false },
    { id: 18, text: "I'll have to get back to you", selected: false },
    { id: 19, text: 'Who just joined?', selected: false },
    { id: 20, text: 'Sorry, something ____ with my calendar', selected: false },
    { id: 21, text: 'Do you see my screen?', selected: false },
    { id: 22, text: "Let's wait for ____!", selected: false },
    { id: 23, text: 'You will send the minutes?', selected: false },
    { id: 24, text: 'Sorry I was on mute.', selected: false },
    { id: 25, text: 'Can you repeat please?', selected: false },
  ],
};

export default configs;
